version: '3.8'

services:
  py-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: py-dev
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    tty: true
    networks:
      - network
    command: sleep infinity

networks:
  network:
    driver: bridge
